// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_gem/test/data/datasources/exercise_local_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i2;

import 'package:fitness_gem/domain/entities/workout_curriculum.dart' as _i6;
import 'package:fitness_gem/domain/entities/workout_task.dart' as _i5;
import 'package:fitness_gem/services/cache_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDirectory_0 extends _i1.SmartFake implements _i2.Directory {
  _FakeDirectory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i3.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Directory> get cacheDirectory =>
      (super.noSuchMethod(
            Invocation.getter(#cacheDirectory),
            returnValue: _i4.Future<_i2.Directory>.value(
              _FakeDirectory_0(this, Invocation.getter(#cacheDirectory)),
            ),
          )
          as _i4.Future<_i2.Directory>);

  @override
  _i4.Future<bool> isCached(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#isCached, [url]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getCachedPath(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPath, [url]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> downloadAndCache(
    String? url, {
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadAndCache,
              [url],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, String?>> downloadMultiple(
    List<String>? urls, {
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadMultiple,
              [urls],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i4.Future<Map<String, String?>>);

  @override
  _i4.Future<bool> cacheWorkoutResources(
    List<_i5.WorkoutTask>? tasks, {
    void Function(int, int, String)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheWorkoutResources,
              [tasks],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> areAllCurriculumResourcesCached(
    _i6.WorkoutCurriculum? curriculum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#areAllCurriculumResourcesCached, [curriculum]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isTaskCached(_i5.WorkoutTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#isTaskCached, [task]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getCacheSize() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheSize, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cleanOldFiles() =>
      (super.noSuchMethod(
            Invocation.method(#cleanOldFiles, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
