// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_gem/test/presentation/viewmodels/home_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:fitness_gem/core/error/failures.dart' as _i7;
import 'package:fitness_gem/domain/entities/user_profile.dart' as _i10;
import 'package:fitness_gem/domain/entities/workout_curriculum.dart' as _i8;
import 'package:fitness_gem/domain/repositories/user_repository.dart' as _i4;
import 'package:fitness_gem/domain/repositories/workout_repository.dart' as _i2;
import 'package:fitness_gem/domain/usecases/user/get_user_profile.dart' as _i14;
import 'package:fitness_gem/domain/usecases/workout/generate_curriculum.dart'
    as _i9;
import 'package:fitness_gem/domain/usecases/workout/get_daily_hot_categories.dart'
    as _i12;
import 'package:fitness_gem/domain/usecases/workout/get_featured_program.dart'
    as _i13;
import 'package:fitness_gem/domain/usecases/workout/get_today_curriculum.dart'
    as _i5;
import 'package:fitness_gem/domain/usecases/workout/save_curriculum.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:fitness_gem/domain/entities/featured_program.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkoutRepository_0 extends _i1.SmartFake
    implements _i2.WorkoutRepository {
  _FakeWorkoutRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRepository_2 extends _i1.SmartFake
    implements _i4.UserRepository {
  _FakeUserRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTodayCurriculumUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodayCurriculumUseCase extends _i1.Mock
    implements _i5.GetTodayCurriculumUseCase {
  MockGetTodayCurriculumUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkoutRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWorkoutRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WorkoutRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.WorkoutCurriculum?>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i6.Future<
                  _i3.Either<_i7.Failure, _i8.WorkoutCurriculum?>
                >.value(
                  _FakeEither_1<_i7.Failure, _i8.WorkoutCurriculum?>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.WorkoutCurriculum?>>);
}

/// A class which mocks [GenerateCurriculumUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateCurriculumUseCase extends _i1.Mock
    implements _i9.GenerateCurriculumUseCase {
  MockGenerateCurriculumUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkoutRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWorkoutRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WorkoutRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.WorkoutCurriculum>> execute(
    _i10.UserProfile? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [params]),
            returnValue:
                _i6.Future<
                  _i3.Either<_i7.Failure, _i8.WorkoutCurriculum>
                >.value(
                  _FakeEither_1<_i7.Failure, _i8.WorkoutCurriculum>(
                    this,
                    Invocation.method(#execute, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.WorkoutCurriculum>>);
}

/// A class which mocks [SaveCurriculumUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveCurriculumUseCase extends _i1.Mock
    implements _i11.SaveCurriculumUseCase {
  MockSaveCurriculumUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkoutRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWorkoutRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WorkoutRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> execute(
    _i8.WorkoutCurriculum? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [params]),
            returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
              _FakeEither_1<_i7.Failure, void>(
                this,
                Invocation.method(#execute, [params]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [GetDailyHotCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDailyHotCategoriesUseCase extends _i1.Mock
    implements _i12.GetDailyHotCategoriesUseCase {
  MockGetDailyHotCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkoutRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWorkoutRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WorkoutRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<String>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, List<String>>>.value(
                  _FakeEither_1<_i7.Failure, List<String>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, List<String>>>);
}

// ... imports

/// A class which mocks [GetFeaturedProgramUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFeaturedProgramUseCase extends _i1.Mock
    implements _i13.GetFeaturedProgramUseCase {
  MockGetFeaturedProgramUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkoutRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWorkoutRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.WorkoutRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i15.FeaturedProgram?>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i6.Future<
                  _i3.Either<_i7.Failure, _i15.FeaturedProgram?>
                >.value(
                  _FakeEither_1<_i7.Failure, _i15.FeaturedProgram?>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i15.FeaturedProgram?>>);
}

/// A class which mocks [GetUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileUseCase extends _i1.Mock
    implements _i14.GetUserProfileUseCase {
  MockGetUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.UserRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i10.UserProfile?>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i10.UserProfile?>>.value(
                  _FakeEither_1<_i7.Failure, _i10.UserProfile?>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i10.UserProfile?>>);
}
