// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_gem/test/data/repositories/exercise_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fitness_gem/data/datasources/exercise_local_datasource.dart'
    as _i4;
import 'package:fitness_gem/data/datasources/exercise_remote_datasource.dart'
    as _i6;
import 'package:fitness_gem/domain/entities/exercise_config.dart' as _i2;
import 'package:fitness_gem/domain/entities/workout_task.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExerciseConfig_0 extends _i1.SmartFake
    implements _i2.ExerciseConfig {
  _FakeExerciseConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutTask_1 extends _i1.SmartFake implements _i3.WorkoutTask {
  _FakeWorkoutTask_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExerciseLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLocalDataSource extends _i1.Mock
    implements _i4.ExerciseLocalDataSource {
  MockExerciseLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ExerciseConfig?> getCachedExerciseConfig(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedExerciseConfig, [url]),
            returnValue: _i5.Future<_i2.ExerciseConfig?>.value(),
          )
          as _i5.Future<_i2.ExerciseConfig?>);

  @override
  _i5.Future<void> cacheExerciseConfig(
    String? url,
    _i2.ExerciseConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheExerciseConfig, [url, config]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.ExerciseConfig> getSampleExerciseConfig(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getSampleExerciseConfig, [taskId]),
            returnValue: _i5.Future<_i2.ExerciseConfig>.value(
              _FakeExerciseConfig_0(
                this,
                Invocation.method(#getSampleExerciseConfig, [taskId]),
              ),
            ),
          )
          as _i5.Future<_i2.ExerciseConfig>);

  @override
  _i5.Future<List<_i3.WorkoutTask>> getLocalWorkoutTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalWorkoutTasks, []),
            returnValue: _i5.Future<List<_i3.WorkoutTask>>.value(
              <_i3.WorkoutTask>[],
            ),
          )
          as _i5.Future<List<_i3.WorkoutTask>>);

  @override
  _i5.Future<void> saveWorkoutTask(_i3.WorkoutTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkoutTask, [task]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteWorkoutTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutTask, [taskId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.WorkoutTask> getSampleWorkoutTask() =>
      (super.noSuchMethod(
            Invocation.method(#getSampleWorkoutTask, []),
            returnValue: _i5.Future<_i3.WorkoutTask>.value(
              _FakeWorkoutTask_1(
                this,
                Invocation.method(#getSampleWorkoutTask, []),
              ),
            ),
          )
          as _i5.Future<_i3.WorkoutTask>);
}

/// A class which mocks [ExerciseRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRemoteDataSource extends _i1.Mock
    implements _i6.ExerciseRemoteDataSource {
  MockExerciseRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ExerciseConfig> fetchExerciseConfig(
    String? url,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchExerciseConfig, [url, category]),
            returnValue: _i5.Future<_i2.ExerciseConfig>.value(
              _FakeExerciseConfig_0(
                this,
                Invocation.method(#fetchExerciseConfig, [url, category]),
              ),
            ),
          )
          as _i5.Future<_i2.ExerciseConfig>);

  @override
  _i5.Future<List<_i3.WorkoutTask>> fetchWorkoutTasks() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWorkoutTasks, []),
            returnValue: _i5.Future<List<_i3.WorkoutTask>>.value(
              <_i3.WorkoutTask>[],
            ),
          )
          as _i5.Future<List<_i3.WorkoutTask>>);
}
