import '../../data/models/workout_task_model.dart';

/// Shared mock data for workouts
const List<WorkoutTaskModel> mockWorkoutTasks = [
  // === Squat ===
  WorkoutTaskModel(
    id: 'squat_01',
    title: 'Box Squat',
    description: 'Box squat is improving form, depth control, and safety',
    advice:
        'Drive up by pushing your heels into the ground and pushing your hips forward, keeping your core engaged.',
    thumbnail: 'assets/images/workouts/squat_01.png',
    readyPoseImageUrl: 'assets/images/workouts/squat_ready.png',
    reps: 15,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'squat_02',
    title: 'Wide Stance Squat',
    description: 'Squat with a wider stance',
    advice: 'Focus on your inner thighs.',
    thumbnail: 'assets/images/workouts/squat_02.png',
    readyPoseImageUrl: 'assets/images/workouts/squat_ready.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'squat_03',
    title: 'Split Squat',
    description: 'One-legged squat with balance maintenance',
    advice: 'Hold one leg and maintain balance.',
    thumbnail: 'assets/images/workouts/squat_03.png',
    readyPoseImageUrl: 'assets/images/workouts/squat_ready.png',
    reps: 8,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 3,
  ),
  WorkoutTaskModel(
    id: 'squat_04',
    title: 'Jump Squat',
    description: 'Explosive squat movement for power.',
    advice: 'Explode upwards and land softly.',
    thumbnail: 'assets/images/workouts/squat_04.png',
    readyPoseImageUrl: 'assets/images/workouts/squat_ready.png',
    reps: 8,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 3,
  ),

  // === Push ===
  WorkoutTaskModel(
    id: 'push_01',
    title: 'Wall Push-up',
    description: 'Push-up against a wall',
    advice: 'Keep your body in a straight line.',
    thumbnail: 'assets/images/workouts/push_01.png',
    readyPoseImageUrl: 'assets/images/workouts/pushup_ready.png',
    reps: 15,
    sets: 3,
    timeoutSec: 60,
    category: 'push',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'push_02',
    title: 'Knee Push-up',
    description: 'Push-up from your knees',
    advice: 'Keep your core engaged.',
    thumbnail: 'assets/images/workouts/push_02.png',
    readyPoseImageUrl: 'assets/images/workouts/pushup_ready.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'push',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'push_03',
    title: 'Standard Push-up',
    description: 'Basic push-up',
    advice: 'Maintain a straight line from head to heels.',
    thumbnail: 'assets/images/workouts/push_03.png',
    readyPoseImageUrl: 'assets/images/workouts/pushup_ready.png',
    reps: 10,
    sets: 3,
    timeoutSec: 60,
    category: 'push',
    difficulty: 3,
  ),

  // === Core ===
  WorkoutTaskModel(
    id: 'core_01',
    title: 'Elbow Plank',
    description: 'Plank on your elbows',
    advice: 'Keep your back flat.',
    thumbnail: 'assets/images/workouts/core_01.png',
    readyPoseImageUrl: 'assets/images/workouts/plank_ready.png',
    reps: 0,
    sets: 3,
    timeoutSec: 30,
    durationSec: 30,
    isCountable: false,
    category: 'core',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'core_02',
    title: 'High Plank',
    description: 'Plank on your hands',
    advice: 'Keep your body in a straight line.',
    thumbnail: 'assets/images/workouts/core_02.png',
    readyPoseImageUrl:
        'assets/images/workouts/pushup_ready.png', // High plank is same as pushup ready
    reps: 0,
    sets: 3,
    timeoutSec: 30,
    durationSec: 40,
    isCountable: false,
    category: 'core',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'core_bird_dog',
    title: 'Bird-Dog',
    description: 'Core stability and balance.',
    advice: 'Keep your hips level and core tight.',
    thumbnail: 'assets/images/workouts/core_03.png',
    readyPoseImageUrl: 'assets/images/workouts/birddog_ready.png',
    reps: 10,
    sets: 3,
    timeoutSec: 45,
    category: 'core',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'core_glute_bridge',
    title: 'Glute Bridge',
    description: 'Strengthen your glutes and hamstrings.',
    advice: 'Squeeze your glutes at the top.',
    thumbnail: 'assets/images/workouts/core_04.png',
    readyPoseImageUrl: 'assets/images/workouts/glutebridge_ready.png',
    reps: 15,
    sets: 3,
    timeoutSec: 45,
    category: 'core',
    difficulty: 1,
  ),

  // === Lunge ===
  WorkoutTaskModel(
    id: 'lunge_01',
    title: 'Static Lunge',
    description: 'Stationary lunge',
    advice: 'Keep your front knee aligned over your ankle.',
    thumbnail: 'assets/images/workouts/lunge_01.png',
    readyPoseImageUrl: 'assets/images/workouts/lunge_ready.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'lunge',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'lunge_02',
    title: 'Forward Lunge',
    description: 'Stepping forward lunge',
    advice: 'Step forward and lower your hips.',
    thumbnail: 'assets/images/workouts/lunge_02.png',
    readyPoseImageUrl: 'assets/images/workouts/lunge_ready.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'lunge',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'lunge_03',
    title: 'Walking Lunge',
    description: 'Lunge while walking',
    advice: 'Maintain balance as you move forward.',
    thumbnail: 'assets/images/workouts/lunge_03.png',
    readyPoseImageUrl: 'assets/images/workouts/lunge_ready.png',
    reps: 10,
    sets: 3,
    timeoutSec: 60,
    category: 'lunge',
    difficulty: 3,
  ),

  // === Explosive / Full Body ===
  WorkoutTaskModel(
    id: 'burpee_01',
    title: 'Classic Burpee',
    description: 'Full body explosive movement.',
    advice: 'Keep a steady rhythm and land softly.',
    thumbnail: 'assets/images/workouts/squat_04.png',
    readyPoseImageUrl: 'assets/images/workouts/burpee_ready.png',
    reps: 10,
    sets: 3,
    timeoutSec: 90,
    category: 'fullbody',
    difficulty: 4,
  ),

  // === Shoulders ===
  WorkoutTaskModel(
    id: 'shoulder_01',
    title: 'Lateral Raise',
    description: 'Sculpt your shoulders with side raises.',
    advice: 'Control the weight on the way down.',
    thumbnail: 'assets/images/workouts/push_01.png',
    readyPoseImageUrl: 'assets/images/workouts/lateral_ready.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'shoulder',
    difficulty: 2,
  ),
];

/// Mock daily hot categories
const List<String> mockDailyHotCategories = [
  'Upper Body',
  'Build Strength',
  'Beginner',
  'Core Workout',
  'Lower Body',
  'HIIT Training',
];

/// Mock featured programs by category
const Map<String, Map<String, dynamic>> mockFeaturedPrograms = {
  'Build Strength': {
    'id': 'summer_shred_mock',
    'title': 'Summer Shred Challenge',
    'slogan': 'Get Set, Stay Ignite.',
    'description': 'High-intensity routine to burn calories and build muscle.',
    'imageUrl': 'assets/images/workouts/squat_04.png',
    'membersCount': '5.8k+',
    'rating': 5.0,
    'difficulty': 3,
    'duration': '18 Min',
    'task_ids': [
      'squat_04',
      'push_03',
      'lunge_03',
      'core_03',
      'squat_03',
      'push_02',
    ],
    'userAvatars': [
      'https://i.pravatar.cc/150?img=11',
      'https://i.pravatar.cc/150?img=12',
      'https://i.pravatar.cc/150?img=33',
    ],
  },
  'Upper Body': {
    'id': 'upper_blast_mock',
    'title': 'Boulder Shoulders 30',
    'slogan': 'Sculpt Your Upper Body.',
    'description': 'Focus on deltoids and chest with this intense circuit.',
    'imageUrl': 'assets/images/workouts/push_01.png',
    'membersCount': '2.1k+',
    'rating': 4.8,
    'difficulty': 4,
    'duration': '20 Min',
    'task_ids': ['push_01', 'push_02', 'core_01', 'core_02'],
    'userAvatars': [
      'https://i.pravatar.cc/150?img=59',
      'https://i.pravatar.cc/150?img=60',
    ],
  },
  'Beginner': {
    'id': 'starter_mock',
    'title': 'Zero to Hero: Week 1',
    'slogan': 'Start Your Journey Today.',
    'description': 'Low impact movements designed for absolute beginners.',
    'imageUrl': 'assets/images/workouts/squat_01.png',
    'membersCount': '12k+',
    'rating': 4.9,
    'difficulty': 1,
    'duration': '10 Min',
    'task_ids': ['squat_01', 'core_01'],
    'userAvatars': [
      'https://i.pravatar.cc/150?img=1',
      'https://i.pravatar.cc/150?img=2',
    ],
  },
};
