import '../../data/models/workout_task_model.dart';

/// Shared mock data for workouts
const List<WorkoutTaskModel> mockWorkoutTasks = [
  // === Squat ===
  WorkoutTaskModel(
    id: 'squat_01',
    title: 'Box Squat',
    description: 'Box squat is improving form, depth control, and safety',
    advice:
        'Drive up by pushing your heels into the ground and pushing your hips forward, keeping your core engaged.',
    thumbnail: 'assets/images/workouts/squat_01.png',
    reps: 15,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'squat_02',
    title: 'Wide Stance Squat',
    description: 'Squat with a wider stance',
    advice: 'Focus on your inner thighs.',
    thumbnail: 'assets/images/workouts/squat_02.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'squat_03',
    title: 'Split Squat',
    description: 'One-legged squat with balance maintenance',
    advice: 'Hold one leg and maintain balance.',
    thumbnail: 'assets/images/workouts/squat_03.png',
    reps: 8,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 3,
  ),
  WorkoutTaskModel(
    id: 'squat_04',
    title: 'Jump Squat',
    description: 'One-legged squat with balance maintenance',
    advice: 'Hold one leg and maintain balance.',
    thumbnail: 'assets/images/workouts/squat_03.png',
    reps: 8,
    sets: 3,
    timeoutSec: 60,
    category: 'squat',
    difficulty: 3,
  ),

  // === Push ===
  WorkoutTaskModel(
    id: 'push_01',
    title: 'Wall Push-up',
    description: 'Push-up against a wall',
    advice: 'Keep your body in a straight line.',
    thumbnail: 'assets/images/workouts/push_01.png',
    reps: 15,
    sets: 3,
    timeoutSec: 60,
    category: 'push',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'push_02',
    title: 'Knee Push-up',
    description: 'Push-up from your knees',
    advice: 'Keep your core engaged.',
    thumbnail: 'assets/images/workouts/push_02.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'push',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'push_03',
    title: 'Standard Push-up',
    description: 'Basic push-up',
    advice: 'Maintain a straight line from head to heels.',
    thumbnail: 'assets/images/workouts/push_03.png',
    reps: 10,
    sets: 3,
    timeoutSec: 60,
    category: 'push',
    difficulty: 3,
  ),

  // === Core ===
  WorkoutTaskModel(
    id: 'core_01',
    title: 'Elbow Plank',
    description: 'Plank on your elbows',
    advice: 'Keep your back flat.',
    thumbnail: 'assets/images/workouts/core_01.png',
    reps: 0,
    sets: 3,
    timeoutSec: 30,
    durationSec: 30,
    isCountable: false,
    category: 'core',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'core_02',
    title: 'High Plank',
    description: 'Plank on your hands',
    advice: 'Keep your body in a straight line.',
    thumbnail: 'assets/images/workouts/core_02.png',
    reps: 0,
    sets: 3,
    timeoutSec: 30,
    durationSec: 40,
    isCountable: false,
    category: 'core',
    difficulty: 2,
  ),

  // === Lunge ===
  WorkoutTaskModel(
    id: 'lunge_01',
    title: 'Static Lunge',
    description: 'Stationary lunge',
    advice: 'Keep your front knee aligned over your ankle.',
    thumbnail: 'assets/images/workouts/lunge_01.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'lunge',
    difficulty: 1,
  ),
  WorkoutTaskModel(
    id: 'lunge_02',
    title: 'Forward Lunge',
    description: 'Stepping forward lunge',
    advice: 'Step forward and lower your hips.',
    thumbnail: 'assets/images/workouts/lunge_02.png',
    reps: 12,
    sets: 3,
    timeoutSec: 60,
    category: 'lunge',
    difficulty: 2,
  ),
  WorkoutTaskModel(
    id: 'lunge_03',
    title: 'Walking Lunge',
    description: 'Lunge while walking',
    advice: 'Maintain balance as you move forward.',
    thumbnail: 'assets/images/workouts/lunge_03.png',
    reps: 10,
    sets: 3,
    timeoutSec: 60,
    category: 'lunge',
    difficulty: 3,
  ),
];
